version: '3.8'

services:
  open-podcraft:
    image: open-podcraft-image:v1
    build:
      context: docker/
      dockerfile: Dockerfile
    container_name: cont-open-podcraft
    runtime: nvidia
    network_mode: "host"
    shm_size: '8g'
    stdin_open: true
    tty: true
    volumes:
      - ./open-podcraft:/root/open-podcraft:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GPU_TYPE=nvidia
    command: tail -f /dev/null
