openrouter_api:
  models: [
    deepseek/deepseek-r1:free,
    deepseek/deepseek-chat:free,
    deepseek/deepseek-r1-distill-llama-70b:free,
    google/gemini-2.0-flash-exp:free,
    google/gemini-2.0-flash-lite-preview-02-05:free,
    google/gemini-2.0-pro-exp-02-05:free,
    google/gemini-exp-1206:free,
    google/gemini-2.0-flash-thinking-exp-1219:free,
    google/gemma-2-9b-it:free,
    google/learnlm-1.5-pro-experimental:free,
    google/gemini-flash-1.5-8b-exp,
    google/gemini-2.0-flash-thinking-exp:free,
    nvidia/llama-3.1-nemotron-70b-instruct:free,
    qwen/qwen2.5-vl-72b-instruct:free,
    qwen/qwen-vl-plus:free,
    meta-llama/llama-3.3-70b-instruct:free,
    meta-llama/llama-3.2-11b-vision-instruct:free,
    meta-llama/llama-3-8b-instruct:free,
    mistralai/mistral-7b-instruct:free,
    mistralai/mistral-nemo:free,    
    mistralai/mistral-small-24b-instruct-2501:free,
    openchat/openchat-7b:free,
    microsoft/phi-3-mini-128k-instruct:free,
    huggingfaceh4/zephyr-7b-beta:free,
    cognitivecomputations/dolphin3.0-r1-mistral-24b:free,
    cognitivecomputations/dolphin3.0-mistral-24b:free,
  ]
    
